"""
comment_builder.py — Builds the final Markdown comment posted on the PR.
All comment formatting lives here, keeping logic and presentation separate.
"""

import textwrap


def build_pr_comment(pr_details: dict, file_reviews: list[tuple[str, str]]) -> str:
    """Assemble the full review comment from per-file reviews."""
    header   = _build_header(pr_details, len(file_reviews))
    sections = _build_file_sections(file_reviews)
    verdict  = _build_verdict(file_reviews)
    return f"{header}\n\n{sections}\n\n{verdict}"


# ── Private helpers ───────────────────────────────────────────────────────────

def _build_header(pr_details: dict, files_reviewed: int) -> str:
    title  = pr_details.get("title", "N/A")
    author = pr_details.get("createdBy", {}).get("displayName", "N/A")
    source = pr_details.get("sourceRefName", "").replace("refs/heads/", "")
    target = pr_details.get("targetRefName", "").replace("refs/heads/", "")

    return textwrap.dedent(f"""\
        # 🤖 AI Code Review — .NET Standards

        | | |
        |---|---|
        | **PR** | {title} |
        | **Author** | {author} |
        | **Branch** | `{source}` → `{target}` |
        | **Files Reviewed** | {files_reviewed} |
        | **Reviewer** | Gemini 1.5 Flash (AI) |

        ---""")


def _build_file_sections(file_reviews: list[tuple[str, str]]) -> str:
    sections = [
        f"## 📄 `{path}`\n\n{review}\n\n---"
        for path, review in file_reviews
    ]
    return "\n\n".join(sections)


def _build_verdict(file_reviews: list[tuple[str, str]]) -> str:
    all_text      = " ".join(r for _, r in file_reviews).lower()
    critical_count = all_text.count("🔴 critical")
    major_count    = all_text.count("🟠 major")

    if critical_count > 0:
        icon    = "🔴"
        verdict = "**Request Changes** — Critical issues must be resolved before merging."
    elif major_count > 2:
        icon    = "🟠"
        verdict = "**Request Changes** — Several major issues found. Address before merging."
    elif major_count > 0:
        icon    = "🟡"
        verdict = "**Needs Discussion** — Some issues found. Consider addressing before merge."
    else:
        icon    = "✅"
        verdict = "**Approved** — Code looks good! No significant issues found."

    return textwrap.dedent(f"""\
        ## {icon} Overall Verdict

        {verdict}

        > *Auto-generated by AI PR Review Agent. Always apply human judgment.*""")
